### ISSUE TITLE
需要个owner的token才能从 https://maven.pkg.github.com/lealone/Lealone下载包？

### ISSUE THREAD

**Issue by gebitang** [lealone/Lealone-Examples#1]
根据文档进行编译，提示未授权。

好像至少需要个owner的token才能从 https://maven.pkg.github.com/lealone/Lealone 下载包？

[Authenticating to GitHub Packages](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages#authenticating-to-github-packages) 

```
D:\openSources\lealonePrj\Lealone-Examples\rpc-demo>build.bat -p
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< org.lealone.demo:lealone-demo >--------------------
[INFO] Building lealone-demo 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/2.3/maven-shade-plugin-2.3.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/2.3/maven-shade-plugin-2.3.pom (0 B at 0 B/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/2.3/maven-shade-plugin-2.3.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/2.3/maven-shade-plugin-2.3.jar (0 B at 0 B/s)
Downloading from github: https://maven.pkg.github.com/lealone/Lealone/org/lealone/lealone-main/5.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.lealone:lealone-main:5.0.0-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/lealone/Lealone): Not authorized
[WARNING] Failure to transfer org.lealone:lealone-main:5.0.0-SNAPSHOT/maven-metadata.xml from https://maven.pkg.github.com/lealone/Lealone was cached in the local repository, resolution will not be reattempted until the update interval of github has elapsed or updates are forced. Original error: Could not transfer metadata org.lealone:lealone-main:5.0.0-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/lealone/Lealone): Not authorized
Downloading from github: https://maven.pkg.github.com/lealone/Lealone/org/lealone/lealone-main/5.0.0-SNAPSHOT/lealone-main-5.0.0-SNAPSHOT.pom
Downloading from github: https://maven.pkg.github.com/lealone/Lealone/org/lealone/lealone-vertx/5.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.lealone:lealone-vertx:5.0.0-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/lealone/Lealone): Not authorized
[WARNING] Failure to transfer org.lealone:lealone-vertx:5.0.0-SNAPSHOT/maven-metadata.xml from https://maven.pkg.github.com/lealone/Lealone was cached in the local repository, resolution will not be reattempted until the update interval of github has elapsed or updates are forced. Original error: Could not transfer metadata org.lealone:lealone-vertx:5.0.0-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/lealone/Lealone): Not authorized
Downloading from github: https://maven.pkg.github.com/lealone/Lealone/org/lealone/lealone-vertx/5.0.0-SNAPSHOT/lealone-vertx-5.0.0-SNAPSHOT.pom
Downloading from github: https://maven.pkg.github.com/lealone/Lealone/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.pom (0 B at 0 B/s)
Downloading from github: https://maven.pkg.github.com/lealone/Lealone/ch/qos/logback/logback-parent/1.1.2/logback-parent-1.1.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-parent/1.1.2/logback-parent-1.1.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-parent/1.1.2/logback-parent-1.1.2.pom (0 B at 0 B/s)
Downloading from github: https://maven.pkg.github.com/lealone/Lealone/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.pom (0 B at 0 B/s)
Downloading from github: https://maven.pkg.github.com/lealone/Lealone/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.pom (0 B at 0 B/s)
Downloading from github: https://maven.pkg.github.com/lealone/Lealone/org/slf4j/slf4j-parent/1.7.6/slf4j-parent-1.7.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.7.6/slf4j-parent-1.7.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.7.6/slf4j-parent-1.7.6.pom (0 B at 0 B/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.779 s
[INFO] Finished at: 2020-10-15T17:04:51+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project lealone-demo: Could not resolve dependencies for project org.lealone.demo:lealone-demo:jar:1.0.0: Failed to collect dependencies at org.lealone:lealone-main:jar:5.0.0-SNAPSHOT: Failed to read artifact descriptor for org.lealone:lealone-main:jar:5.0.0-SNAPSHOT: Could not transfer artifact org.lealone:lealone-main:pom:5.0.0-SNAPSHOT from/to github (https://maven.pkg.github.com/lealone/Lealone): Failed to transfer file https://maven.pkg.github.com/lealone/Lealone/org/lealone/lealone-main/5.0.0-SNAPSHOT/lealone-main-5.0.0-SNAPSHOT.pom with status code 400 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

D:\openSources\lealonePrj\Lealone-Examples\rpc-demo>
```

**Comment by gebitang** [comment]
从源码编译安装了 依赖的 lealone-main和lealone-vertx之后，可以打包成功。 运行时提示  java.lang.NoSuchFieldError: defaultLockTimeout


```
D:\openSources\lealonePrj\Lealone-Examples\rpc-demo>build.bat -r
INFO 17:30:36.529 web root: ./web
INFO 17:30:36.532 sockjs path: /_lealone_sockjs_/*
INFO 17:30:36.532 http server is now listening on port: 8080
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.lealone.db.session.ServerSessionFactory.createServerSession(ServerSessionFactory.java:49)
        at org.lealone.db.session.ServerSessionFactory.createSession(ServerSessionFactory.java:43)
        at org.lealone.db.session.SessionFactory.createSession(SessionFactory.java:24)
        at org.lealone.client.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
        at org.lealone.client.jdbc.JdbcConnection.<init>(JdbcConnection.java:84)
        at org.lealone.client.jdbc.JdbcDriver.connect(JdbcDriver.java:54)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at org.lealone.demo.DemoApplication.createService(DemoApplication.java:37)
        at org.lealone.demo.DemoApplication.main(DemoApplication.java:25)
Caused by: org.lealone.common.exceptions.DbException: General error: "java.lang.NoSuchFieldError: defaultLockTimeout" [50000-0]
        at org.lealone.common.exceptions.DbException.get(DbException.java:164)
        at org.lealone.common.exceptions.DbException.convert(DbException.java:283)
        at org.lealone.db.Database.openDatabase(Database.java:513)
        at org.lealone.db.Database.init(Database.java:423)
        at org.lealone.db.LealoneDatabase.<init>(LealoneDatabase.java:66)
        at org.lealone.db.LealoneDatabase.<clinit>(LealoneDatabase.java:44)
        ... 10 more
Caused by: org.lealone.common.exceptions.JdbcSQLException: General error: "java.lang.NoSuchFieldError: defaultLockTimeout" [50000-0]
        at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:335)
        ... 16 more
Caused by: java.lang.NoSuchFieldError: defaultLockTimeout
        at org.lealone.db.session.ServerSession.<init>(ServerSession.java:137)
        at org.lealone.db.session.SystemSession.<init>(SystemSession.java:27)
        at org.lealone.db.Database.openDatabase(Database.java:489)
        ... 13 more


```

**Comment by gebitang** [comment]
![dbsettings](https://user-images.githubusercontent.com/1187857/96110321-47997780-0f12-11eb-9065-473b02cd7644.png)

本地调试，进入`ServerSession`构造方法后，默认的 DbSettings里此时的确没有`defaultLockTimeout` 这个属性。

什么情况导致的这个场景呢？

**Comment by codefollower** [comment]
> ![dbsettings](https://user-images.githubusercontent.com/1187857/96110321-47997780-0f12-11eb-9065-473b02cd7644.png)
> 
> 本地调试，进入`ServerSession`构造方法后，默认的 DbSettings里此时的确没有`defaultLockTimeout` 这个属性。
> 
> 什么情况导致的这个场景呢？

看看org.lealone.db.DbSettings这个类的源代码是否有defaultLockTimeout这个字段，如果没有就更新一下源代码重新编译。

**Comment by codefollower** [comment]
需要owner的token才能从 https://maven.pkg.github.com/lealone/Lealone 下载包这个问题我特意修改maven settings之后确实发现不能下，我还不知道github为什么会这样，或者在哪里配成不要token。

**Comment by gebitang** [comment]
> 看看org.lealone.db.DbSettings这个类的源代码是否有defaultLockTimeout这个字段，如果没有就更新一下源代码重新编译。

lealone-db的源码里有，lealone-common的源码里没有。执行 `build.bat -p`的时候给出了warning

看起来是加载的问题， ` org.lealone.db.DbSettings`这个类在两个jar包下都

```
[INFO] Including ch.qos.logback:logback-core:jar:1.1.2 in the shaded jar.
[INFO] Including ch.qos.logback:logback-classic:jar:1.1.2 in the shaded jar.
[WARNING] lealone-common-5.0.0-SNAPSHOT.jar, lealone-db-5.0.0-SNAPSHOT.jar define 2 overlappping classes:
[WARNING]   - org.lealone.db.DbSettings
[WARNING]   - org.lealone.db.SettingsBase
[WARNING] jackson-databind-2.10.2.jar, jackson-core-2.10.2.jar, jackson-annotations-2.10.2.jar define 1 overlappping classes:
[WARNING]   - module-info
[WARNING] maven-shade-plugin has detected that some .class files
[WARNING] are present in two or more JARs. When this happens, only
[WARNING] one single version of the class is copied in the uberjar.
[WARNING] Usually this is not harmful and you can skeep these
[WARNING] warnings, otherwise try to manually exclude artifacts
[WARNING] based on mvn dependency:tree -Ddetail=true and the above
[WARNING] output

```

**Comment by gebitang** [comment]
> 需要owner的token才能从 https://maven.pkg.github.com/lealone/Lealone 下载包这个问题我特意修改maven settings之后确实发现不能下，我还不知道github为什么会这样，或者在哪里配成不要token。

好像必须要进行验证。可以创建一个 只有 `read:package`权限的token公布出来？

https://stackoverflow.com/a/58453517 

```
GitHub > Settings > Developer Settings > Personal access tokens > Generate new token:
The token needs at least the read:packages scope. Otherwise you will get a Not authorized exception.
```

**Comment by codefollower** [comment]
我编译出来的lealone-common-5.0.0-SNAPSHOT.jar没有那两个类，不存在你说的那个编译警告。有可能是lealone-common里面有之前的老版本，你把本地maven库删除再安装一下看看。

**Comment by codefollower** [comment]
token不跟项目绑定的，他那个的意思是说你自己创建一个token然后就可以用它下别人的包了吧？

**Comment by gebitang** [comment]
> 我编译出来的lealone-common-5.0.0-SNAPSHOT.jar没有那两个类，不存在你说的那个编译警告。有可能是lealone-common里面有之前的老版本，你把本地maven库删除再安装一下看看。

 lealone-common里包含[DbSettings.java](https://github.com/lealone/Lealone/blob/master/lealone-common/src/main/java/org/lealone/db/DbSetting.java) 这个类。 我在 lealone项目下执行 `build.bat -i `安装的common包，打包的文件里包含这个类。

demo项目的依赖树—— 同时包含了common和db包。
```
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ lealone-demo ---
[INFO] org.lealone.demo:lealone-demo:jar:1.0.0
[INFO] +- org.lealone:lealone-main:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- org.lealone:lealone-client:jar:5.0.0-SNAPSHOT:compile
[INFO] |  |  \- org.lealone:lealone-net:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- org.lealone:lealone-server:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- org.lealone:lealone-aote:jar:5.0.0-SNAPSHOT:compile
[INFO] |  |  \- org.lealone:lealone-common:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- org.lealone:lealone-aose:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- org.lealone:lealone-sql:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- org.lealone:lealone-p2p:jar:5.0.0-SNAPSHOT:compile
[INFO] |  |  +- com.yammer.metrics:metrics-core:jar:2.2.0:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.11:compile
[INFO] |  \- org.lealone:lealone-orm:jar:5.0.0-SNAPSHOT:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-core:jar:2.10.2:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.2:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.2:compile
[INFO] +- org.lealone:lealone-vertx:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- org.lealone:lealone-db:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- io.vertx:vertx-core:jar:3.9.0:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.48.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.48.Final:compile
[INFO] |  |  +- io.netty:netty-transport:jar:4.1.48.Final:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.48.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.48.Final:compile
[INFO] |  |  +- io.netty:netty-handler-proxy:jar:4.1.48.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec-socks:jar:4.1.48.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.48.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.48.Final:compile
[INFO] |  |  +- io.netty:netty-resolver:jar:4.1.48.Final:compile
[INFO] |  |  \- io.netty:netty-resolver-dns:jar:4.1.48.Final:compile
[INFO] |  |     \- io.netty:netty-codec-dns:jar:4.1.48.Final:compile
[INFO] |  +- io.vertx:vertx-jdbc-client:jar:3.9.0:compile
[INFO] |  |  +- io.vertx:vertx-sql-common:jar:3.9.0:compile
[INFO] |  |  \- com.mchange:c3p0:jar:0.9.5.4:compile
[INFO] |  |     \- com.mchange:mchange-commons-java:jar:0.2.15:compile
[INFO] |  \- io.vertx:vertx-web:jar:3.9.0:compile
[INFO] |     +- io.vertx:vertx-web-common:jar:3.9.0:compile
[INFO] |     +- io.vertx:vertx-auth-common:jar:3.9.0:compile
[INFO] |     \- io.vertx:vertx-bridge-common:jar:3.9.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.2:compile
[INFO] +- ch.qos.logback:logback-core:jar:1.1.2:compile
[INFO] \- ch.qos.logback:logback-classic:jar:1.1.2:compile
```

这个报错是因为这个问题导致的，我再看看如何才能避免。

**Comment by gebitang** [comment]
> token不跟项目绑定的，他那个的意思是说你自己创建一个token然后就可以用它下别人的包了吧？

应该公开一个这样的token应该就可以了——

![read-pakages-token](https://user-images.githubusercontent.com/1187857/96120710-871b9000-0f21-11eb-9493-4fa5b9298d3e.png)


- demo项目要使用你的GitHub Packages仓库
- 读取这个仓库需要对应的权限，
- 权限可以通过用户名、密码（这种方式只能你自己用）；或token方式（公共使用，只包含 `read:packages`权限）

**Comment by codefollower** [comment]
lealone-common里包含的是DbSetting.java，不是DbSettings.java，少了个s的。我建议你确认一下两个模块的源文件是否有同名的类，然后把maven本地库删一下。如果你之前下过源代码，可能因为重构了很多次后，pull源代码有时不知道git为何没有删除之前的老文件。这种问提我pull其他开源项目时也碰到过。

**Comment by gebitang** [comment]
> lealone-common里包含的是DbSetting.java，不是DbSettings.java，少了个s的。我建议你确认一下两个模块的源文件是否有同名的类，然后把maven本地库删一下。如果你之前下过源代码，可能因为重构了很多次后，pull源代码有时不知道git为何没有删除之前的老文件。这种问提我pull其他开源项目时也碰到过。

是这个原因。

本地有旧的lealone的源码class，直接执行 `build.bat -i`会直接使用旧的class。重新编译打包lealone-common后，现在正常了

![worked](https://user-images.githubusercontent.com/1187857/96122810-a7008300-0f24-11eb-9f8d-8436dab07a84.png)
