### ISSUE TITLE
lealone微服务定义问题

### ISSUE THREAD

**Issue by jiliapp** [lealone/Lealone-Examples#11]
###  创建服务: user_service

````
-- 创建服务: user_service，会生成一个对应的 userService 接口
create service if not exists user_service (
    get_user_list(user user) java.util.List<user>,
    login(name varchar, password varchar) user,
    logout(user_id varchar) varchar,
    register(name varchar, password varchar) user,
    get_user(user_id long) user,
    find_by_name(name varchar) varchar
)
````
1. lealone定义微服务，可以返回类似get_user_list(user user) java.util.List<user>,集合或者其他自定义的对象么？
2. get_user(user_id long) user, 生成后，实现直接返回的User对象，在客户端看到的json字符串如下：
````
{
    "ID": 2,
    "NAME": "lisi",
    "PASSWORD": "123456",
    "modelType": 0
}

````
key字段是大写的。

**Comment by codefollower** [comment]
目前暂不支持返回 list、map、set 类型，sql 标准 只有一个 array 类型跟 list 接近。

数据库内部的表名字段名默认是大写的，创建数据库时可以使用 create database mydb parameters(database_to_upper=false) 这样就不会自动转大写了。

**Comment by codefollower** [comment]
如果想返回  list、map、set 或其他对象，可以把返回类型变成 varchar，
lealone orm 框架有两个工具类，org.lealone.orm.json.JsonObject 和 org.lealone.orm.json.JsonArray
用它俩可以把大部分常用的 java 类型转成  json 字符串

petstore 这个演示项目里就是这么做的，或者用其他 json 库也可以，lealone 不想强制应用使用某个框架和库，所以没有提供 api。

只有根据表生成的 Model 对象，才会自动转成 json。

**Comment by jiliapp** [comment]
petstore已经看过了，临时方案可以这样子做。理论上接口不能定义返回一个“混沌”的string定义(实际是想返回对象)，让调用端来猜返回的是啥吧。

**Comment by codefollower** [comment]
lealone 定义的服务，不只限于通过前端来调用，还得满足通过 jdbc 的调用方式。
list 类型可以用 array 类型替代，jdbc 和 sql 标准都是原生支持 array 类型的，
如果要支持 set 和 map，实际上需要在数据库里额外支持两种复合类型，
就算支持了，jdbc 没有对应的 api 也用不了这种复合类型。

**Comment by codefollower** [comment]
lealone 定义的服务，不只限于通过前端来调用，还得满足通过 jdbc 的调用方式。
list 类型可以用 array 类型替代，jdbc 和 sql 标准都是原生支持 array 类型的，
如果要支持 set 和 map，实际上需要在数据库里额外支持两种复合类型，
就算支持了，jdbc 没有对应的 api 也用不了这种复合类型。

**Comment by codefollower** [comment]
list 和 set 可以用 array 替代。

参数类型和返回类型也不要用 map，用了 map 还得进一步写个文档告诉别人 map 里有哪些 key 可用，对应的类型是什么，这时你可以建一张表来替换 map。

在 lealone 里参数类型和返回类型都可以是一张表， lealone 原生支持表类型的参数和返回值，非常好用。如果用 map，在后端你得用字符串的 key 操作，一旦前端把 key 修改了，后端重构好麻烦的，用表的话会对应一个模型类，是静态类型安全的，重构非常方便。

**Comment by jiliapp** [comment]
> create database mydb parameters(database_to_upper=false)
修改VoiceSqlScript中的语句，支持小写字段。
````
  //runSql(jdbcUrl, "create database if not exists voice");
  runSql(jdbcUrl, "create database if not exists voice parameters(database_to_upper=false)");

````
UserServiceExecutor报错，找不到大写的服务名称GET_USER。
````
ERROR 09:23:57.709 failed to execute service: voice.public.user_service, cause: no method: GET_USER
java.lang.RuntimeException: no method: GET_USER
	at cn.jiliapp.voice.service.generated.executor.UserServiceExecutor.executeService(UserServiceExecutor.java:107) ~[classes/:?]
	at org.lealone.db.service.Service.execute(Service.java:125) ~[lealone-db-5.0.0-20220422.064507-27.jar:?]
	at org.lealone.server.http.HttpServiceHandler.executeService(HttpServiceHandler.java:59) ~[lealone-web-5.0.0-20220422.064944-21.jar:?]
	at org.lealone.server.http.HttpRouterFactory.handleHttpServiceRequest(HttpRouterFactory.java:115) ~[lealone-web-5.0.0-20220422.064944-21.jar:?]
	at org.lealone.server.http.HttpRouterFactory.lambda$0(HttpRouterFactory.java:103) ~[lealone-web-5.0.0-20220422.064944-21.jar:?]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1104) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:131) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:290) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:86) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63) ~[vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76) ~[vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:561) ~[vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.http.impl.Http1xServerRequest.handleEnd(Http1xServerRequest.java:544) ~[vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71) [vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163) [vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.http.impl.Http1xServerConnection.onEnd(Http1xServerConnection.java:191) [vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:147) [vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155) [vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153) [vertx-core-4.2.6.jar:4.2.6]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99) [netty-codec-http-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61) [vertx-core-4.2.6.jar:4.2.6]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38) [vertx-core-4.2.6.jar:4.2.6]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.74.Final.jar:4.1.74.Final]


````
实际已经变成小写的服务名称了。当然找不到了。

````
        case "get_user":
            Long p_userId_5 = Long.valueOf(ServiceExecutor.toString("user_id", methodArgs));
            User result5 = this.s.getUser(p_userId_5);
            if (result5 == null)
                return null;
            return result5.encode();
````

**Comment by jiliapp** [comment]
当然，我自己修改case "get_user": 为 case "GET_USER": 前端显示正确。
````
{
    "id": 1,
    "name": "zhangsan",
    "password": "123456",
    "modelType": 0
}

````

**Comment by codefollower** [comment]
你在 create service 之前加一条 drop service 语句，这样每次执行 services.sql 时就会生成新的服务代码了。
代码没有 bug 的，刷新一下 IDE 看看里面生成的 XXXServiceExecutor 有没有变成小写就知道了，我这里测试都是正常的。

**Comment by jiliapp** [comment]
XXXServiceExecutor 中的名称是变成小写了的，我说的是参数methodName还是原来的大写的。所以在case中就找不到了。

**Comment by codefollower** [comment]
明白了，你说的是从前端调用。

**Comment by jiliapp** [comment]
> lealone 定义的服务，不只限于通过前端来调用，还得满足通过 jdbc 的调用方式。
> list 类型可以用 array 类型替代，jdbc 和 sql 标准都是原生支持 array 类型的，
> 如果要支持 set 和 map，实际上需要在数据库里额外支持两种复合类型，
> 就算支持了，jdbc 没有对应的 api 也用不了这种复合类型。

我以为lealone定义的微服务和数据库无关的，因为在xxServiceImpl实现类中我是用lealoneORM实现查找数据，如下：
````
    @Override
    public String getList() {
        List<User> users= User.dao.where().findList();
        JsonObject json = new JsonObject();
        json.put("users",users);
        return json.encode();
    }
````
List<User> users= User.dao.where().findList(); 这一句已经找到了我需要的list列表。

**Comment by codefollower** [comment]
可以了，更新一下代码试试看

**Comment by codefollower** [comment]
lealone 定义的微服务和数据库肯定是相关的，create service 语句创建的 Service 对象就是通过 database、schema 查找出来的，甚至可以直接用 sql 的方式调用服务，比如 execute service user_service add(?)

你看看生成的代码里那个 UserService 接口，里面就有一个 ServiceProxy，就是通过 sql 调用后端服务。
这样别的后端业务系统想调用你的 UserService，你只需要把这个 UserService 接口给别人，
然后别人就可以这样调用了:
```java
User user = new User();
UserService userService = UserService.create();
userService.add(user);
```
如果后端其他业务系统只喜欢 http rest 的方式，或者是用其他语言开发，只要有 http client 相关的库就跟在前端一样调用。

**Comment by codefollower** [comment]
`List<User> users= User.dao.where().findList();` 
可以改成
`List<User> users= User.dao.findList();`
where() 是可选的，只有带条件时才建议加上，增加可读性。

**Comment by codefollower** [comment]
lealone orm 框架新的代码增加了一个 findArray

定义服务时，在 get_list 那里可以返回 array

然后把以下代码
```java
    @Override
    public String getList() {
        List<User> users= User.dao.where().findList();
        JsonObject json = new JsonObject();
        json.put("users",users);
        return json.encode();
    }
```
可以改成
```java
    @Override
    public Array getList() {
        return User.dao.findArray();
    }
```

**Comment by codefollower** [comment]
lealone 5.1.0-SNAPSHOT 已经支持 set、list、map 类型

用法:
```sql
create service if not exists my_service (
 m1() set<int>,
 m2() list<varchar(10)>,
 m3() map<int, varchar>
);
```
