### ISSUE TITLE
通过源代码编译利用LeaLone，运行PetStore报NoSuchMethodError

### ISSUE THREAD

**Issue by liujian16** [lealone/Lealone-Examples#2]
因为PetStore依赖的Lealone无法从github下载，clone了LeaLone的源代码，install到本地仓库。

运行PetStoreDemoTest报NoSuchMethodError

```
INFO 09:49:20.908 Lealone version: 5.0.0-SNAPSHOT
INFO 09:49:20.922 Loading config from file:/Users/xxx/codework/Lealone-Examples/petstore/petstore-test/target/test-classes/lealone.yaml
INFO 09:49:21.061 Base dir: ./target/data
INFO 09:49:21.134 Init storage engines: 13 ms
INFO 09:49:21.273 Init transaction engines: 138 ms
INFO 09:49:21.279 Init sql engines: 4 ms
INFO 09:49:21.329 Init protocol server engines: 49 ms
INFO 09:49:21.540 Init lealone database: 211 ms
INFO 09:49:21.540 Starting nio net server
INFO 09:49:21.570 TcpServer started, host: 127.0.0.1, port: 9210
INFO 09:49:22.241 Web root: ../petstore-web/web
INFO 09:49:22.242 Sockjs path: /_lealone_sockjs_/*
INFO 09:49:22.242 HttpServer is now listening on port: 9000
INFO 09:49:22.242 HttpServer started, host: 127.0.0.1, port: 9000
INFO 09:49:22.242 Total time: 1329 ms (Load config: 148 ms, Init: 479 ms, Start: 702 ms)
INFO 09:49:22.242 Exit with Ctrl+C
Exception in thread "PeriodicLogSyncService" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.lealone.db.DataBuffer.getAndFlipBuffer(DataBuffer.java:497)
	at org.lealone.transaction.aote.log.RedoLogChunk.write(RedoLogChunk.java:133)
	at org.lealone.transaction.aote.log.RedoLogChunk.save(RedoLogChunk.java:117)
	at org.lealone.transaction.aote.log.RedoLog.save(RedoLog.java:147)
	at org.lealone.transaction.aote.log.LogSyncService.sync(LogSyncService.java:101)
	at org.lealone.transaction.aote.log.LogSyncService.run(LogSyncService.java:76)
```
<img width="946" alt="屏幕快照 2020-12-31 09 55 46" src="https://user-images.githubusercontent.com/1186244/103390281-8c669f00-4b4e-11eb-9014-9dc2c24a08f3.png">

**Comment by liujian16** [comment]
问题解决了。原因是我编译LeaLone是用的是Java 11， 换成Java 8就好了。 具体原因参见 https://github.com/plasma-umass/doppio/issues/497#issuecomment-334740243
