### ISSUE TITLE
windows idea下运行orm-demo报错

### ISSUE THREAD

**Issue by zhangyou1010** [lealone/Lealone-Examples#24]
D:\opt\Java\jdk-17.0.5\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.3\lib\idea_rt.jar=7925:C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.3\bin" -Dfile.encoding=UTF-8 -classpath H:\项目\Lealone-Examples-main\orm-demo\target\classes;C:\opt\repo\org\lealone\plugins\lealone-orm\5.0.0\lealone-orm-5.0.0.jar;C:\opt\repo\org\lealone\lealone-sql\5.0.0\lealone-sql-5.0.0.jar;C:\opt\repo\org\lealone\lealone-db\5.0.0\lealone-db-5.0.0.jar;C:\opt\repo\org\lealone\lealone-client\5.0.0\lealone-client-5.0.0.jar;C:\opt\repo\org\lealone\lealone-net\5.0.0\lealone-net-5.0.0.jar;C:\opt\repo\org\lealone\lealone-aote\5.0.0\lealone-aote-5.0.0.jar;C:\opt\repo\org\lealone\lealone-common\5.0.0\lealone-common-5.0.0.jar;C:\opt\repo\org\apache\logging\log4j\log4j-core\2.17.1\log4j-core-2.17.1.jar;C:\opt\repo\org\apache\logging\log4j\log4j-api\2.17.1\log4j-api-2.17.1.jar;C:\opt\repo\org\lealone\lealone-aose\5.0.0\lealone-aose-5.0.0.jar;C:\opt\repo\com\fasterxml\jackson\core\jackson-core\2.13.1\jackson-core-2.13.1.jar;C:\opt\repo\junit\junit\4.8\junit-4.8.jar org.lealone.examples.orm.OrmDemo
Exception in thread "main" org.lealone.common.exceptions.JdbcSQLException: IO Exception: "java.io.FileNotFoundException: .\src\main\resources\tables.sql (系统找不到指定的路径。)"; "./src/main/resources/tables.sql"; SQL statement:
RUNSCRIPT FROM './src/main/resources/tables.sql' [90031-0]
	at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:342)
	at org.lealone.common.exceptions.DbException.get(DbException.java:162)
	at org.lealone.common.exceptions.DbException.convertIOException(DbException.java:327)
	at org.lealone.sql.dml.ScriptBase.openInput(ScriptBase.java:162)
	at org.lealone.sql.dml.RunScript.update(RunScript.java:53)
	at org.lealone.sql.executor.YieldableLocalUpdate.executeInternal(YieldableLocalUpdate.java:23)
	at org.lealone.sql.executor.YieldableBase.run(YieldableBase.java:97)
	at org.lealone.sql.StatementBase.syncExecute(StatementBase.java:521)
	at org.lealone.sql.StatementBase.executeUpdate(StatementBase.java:580)
	at org.lealone.client.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:231)
	at org.lealone.client.jdbc.JdbcStatement.executeUpdateSync(JdbcStatement.java:218)
	at org.lealone.client.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:141)
	at org.lealone.examples.orm.OrmDemo.createTable(OrmDemo.java:126)
	at org.lealone.examples.orm.OrmDemo.main(OrmDemo.java:34)
Caused by: java.io.FileNotFoundException: .\src\main\resources\tables.sql (系统找不到指定的路径。)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at org.lealone.storage.fs.FilePathDisk.newInputStream(FilePathDisk.java:314)
	at org.lealone.storage.fs.FileUtils.newInputStream(FileUtils.java:217)
	at org.lealone.sql.dml.ScriptBase.openInput(ScriptBase.java:160)
	... 10 more

Process finished with exit code 1

**Comment by codefollower** [comment]
我这里是没有问题的，你直接在 idea 里 open，然后把 orm-demo 的代码导进去就可以了。
Lealone-Examples 里的例子都是标准的 maven 项目，idea 都能直接 open 的，最后在 idea 里直接运行 OrmDemo 即可。

如果找不到文件，多半是你的 idea 的当前工作路径不是在 lealone-examples\orm-demo 下面，
正常情况下，把 orm-demo 的代码导进 idea，会在 lealone-examples\orm-demo 下面多一个 .idea 目录。

![image](https://user-images.githubusercontent.com/872655/198174420-eb9cec3f-d364-49ad-8d91-4319928e2186.png)
![image](https://user-images.githubusercontent.com/872655/198174455-2b816595-cc6d-440b-902a-3ee89858c276.png)

**Comment by zhangyou1010** [comment]
谢谢回复，我是把Lealone-Examples-main整个导入idea的，单独把orm-demo可以正常运行了。
