### ISSUE TITLE
petstore 添加产品失败，不知道从哪里开始定位

### ISSUE THREAD

**Issue by zhangyou1010** [lealone/Lealone-Examples#25]
请求信息：

http://localhost:9000/service/store_service/add_product

{"categoryid":"BIRDS","productid":"BIRDS1","name":"BIRDS1","descn":"BIRDS1"}

idea控制台报错：

`INFO 11:15:33.560 execute service: petstore.public.store_service.add_product
INFO 11:15:33.562 execute sql: INSERT INTO PUBLIC.PRODUCT(LOGO)
VALUES (STRINGDECODE('\u5c0fQ\u622a\u56fe-20220311135921.png'))
ERROR 11:15:33.569 failed to execute service: petstore.public.store_service.add_product, cause: NULL not allowed for column "PRODUCTID" [23502-0]
org.lealone.common.exceptions.DbException: NULL not allowed for column "PRODUCTID" [23502-0]
	at org.lealone.common.exceptions.DbException.get(DbException.java:173) ~[lealone-common-5.0.0.jar:?]
	at org.lealone.common.exceptions.DbException.get(DbException.java:150) ~[lealone-common-5.0.0.jar:?]
	at org.lealone.db.table.Column.validateConvertUpdateSequence(Column.java:295) ~[lealone-db-5.0.0.jar:?]
	at org.lealone.db.table.Table.validateConvertUpdateSequence(Table.java:682) ~[lealone-db-5.0.0.jar:?]
	at org.lealone.sql.dml.MerSert$YieldableInsertBase.addRowInternal(MerSert.java:204) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.sql.dml.Insert$YieldableInsert.executeLoopUpdate(Insert.java:92) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.sql.executor.YieldableLoopUpdateBase.executeInternal(YieldableLoopUpdateBase.java:30) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.sql.executor.YieldableBase.run(YieldableBase.java:97) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.sql.StatementBase.syncExecute(StatementBase.java:521) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.sql.StatementBase.executeUpdate(StatementBase.java:580) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.plugins.orm.Model.insert(Model.java:787) ~[lealone-orm-5.0.0.jar:?]
	at org.lealone.plugins.orm.Model.insert(Model.java:752) ~[lealone-orm-5.0.0.jar:?]
	at org.lealone.examples.petstore.service.StoreService.addProduct(StoreService.java:32) ~[classes/:?]
	at org.lealone.examples.petstore.service.executor.StoreServiceExecutor.executeService(StoreServiceExecutor.java:51) ~[?:?]
	at org.lealone.db.service.Service.execute(Service.java:157) ~[lealone-db-5.0.0.jar:?]
	at org.lealone.plugins.service.ServiceHandler.executeService(ServiceHandler.java:45) ~[lealone-service-5.0.0.jar:?]
	at org.lealone.plugins.service.ServiceHandler.executeService(ServiceHandler.java:28) ~[lealone-service-5.0.0.jar:?]
	at org.lealone.plugins.vertx.VertxRouter.handleHttpServiceRequest(VertxRouter.java:123) ~[lealone-vertx-5.0.0.jar:?]
	at org.lealone.plugins.vertx.VertxRouter.lambda$setHttpServiceHandler$0(VertxRouter.java:109) ~[lealone-vertx-5.0.0.jar:?]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:136) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:46) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140) ~[vertx-web-4.3.1.jar:4.3.1]
	at org.lealone.examples.petstore.web.PetStoreRouter.lambda$setFileUploadHandler$4(PetStoreRouter.java:76) ~[classes/:?]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:355) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.uploadEnded(BodyHandlerImpl.java:321) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.lambda$null$0(BodyHandlerImpl.java:250) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.lealone.common.exceptions.JdbcSQLException: NULL not allowed for column "PRODUCTID" [23502-0]
	at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:342) ~[lealone-common-5.0.0.jar:?]
	... 59 more
ERROR 11:15:33.572 Unhandled exception in router
org.lealone.common.exceptions.DbException: NULL not allowed for column "PRODUCTID" [23502-0]
	at org.lealone.common.exceptions.DbException.get(DbException.java:173) ~[lealone-common-5.0.0.jar:?]
	at org.lealone.common.exceptions.DbException.get(DbException.java:150) ~[lealone-common-5.0.0.jar:?]
	at org.lealone.db.table.Column.validateConvertUpdateSequence(Column.java:295) ~[lealone-db-5.0.0.jar:?]
	at org.lealone.db.table.Table.validateConvertUpdateSequence(Table.java:682) ~[lealone-db-5.0.0.jar:?]
	at org.lealone.sql.dml.MerSert$YieldableInsertBase.addRowInternal(MerSert.java:204) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.sql.dml.Insert$YieldableInsert.executeLoopUpdate(Insert.java:92) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.sql.executor.YieldableLoopUpdateBase.executeInternal(YieldableLoopUpdateBase.java:30) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.sql.executor.YieldableBase.run(YieldableBase.java:97) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.sql.StatementBase.syncExecute(StatementBase.java:521) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.sql.StatementBase.executeUpdate(StatementBase.java:580) ~[lealone-sql-5.0.0.jar:?]
	at org.lealone.plugins.orm.Model.insert(Model.java:787) ~[lealone-orm-5.0.0.jar:?]
	at org.lealone.plugins.orm.Model.insert(Model.java:752) ~[lealone-orm-5.0.0.jar:?]
	at org.lealone.examples.petstore.service.StoreService.addProduct(StoreService.java:32) ~[classes/:?]
	at org.lealone.examples.petstore.service.executor.StoreServiceExecutor.executeService(StoreServiceExecutor.java:51) ~[?:?]
	at org.lealone.db.service.Service.execute(Service.java:157) ~[lealone-db-5.0.0.jar:?]
	at org.lealone.plugins.service.ServiceHandler.executeService(ServiceHandler.java:45) ~[lealone-service-5.0.0.jar:?]
	at org.lealone.plugins.service.ServiceHandler.executeService(ServiceHandler.java:28) ~[lealone-service-5.0.0.jar:?]
	at org.lealone.plugins.vertx.VertxRouter.handleHttpServiceRequest(VertxRouter.java:123) ~[lealone-vertx-5.0.0.jar:?]
	at org.lealone.plugins.vertx.VertxRouter.lambda$setHttpServiceHandler$0(VertxRouter.java:109) ~[lealone-vertx-5.0.0.jar:?]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:136) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:46) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140) ~[vertx-web-4.3.1.jar:4.3.1]
	at org.lealone.examples.petstore.web.PetStoreRouter.lambda$setFileUploadHandler$4(PetStoreRouter.java:76) ~[classes/:?]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:355) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.uploadEnded(BodyHandlerImpl.java:321) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.lambda$null$0(BodyHandlerImpl.java:250) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.lealone.common.exceptions.JdbcSQLException: NULL not allowed for column "PRODUCTID" [23502-0]
	at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:342) ~[lealone-common-5.0.0.jar:?]
	... 59 more
`

**Comment by zhangyou1010** [comment]
public String addProduct(Product product, String logo) {
        product.logo.set(logo);
        product.insert();
        return null;
    }

这个方法里面传进来的product 字段的value都为null

**Comment by zhangyou1010** [comment]
执行org.lealone.db.service.Service里面的execute方法时，参数丢了？

**Comment by zhangyou1010** [comment]
请问这个类org.lealone.examples.petstore.service.executor.StoreServiceExecutor是动态生成的字节码吗？ 貌似这个执行有问题？

**Comment by codefollower** [comment]
我查一下，之前还好好的，后来升级一下 vertx 的版本就出 bug 了，也可能是其他原因。

服务执行器都是动态生成的。

**Comment by codefollower** [comment]
前端传来的 json 是小写的，model 的字段名是大写的，所以从 json 解码时就没找到字段，Product product 就没有设置字段了，所以 insert 就抛出异常 NULL not allowed for column "PRODUCTID"

问题已经修复，你更新一下代码重试一下。

**Comment by zhangyou1010** [comment]
model里面字段是小写的：

`public class Product extends Model<Product> {

    public static final Product dao = new Product(null, ROOT_DAO);

    public final PString<Product> productid;
    public final PString<Product> categoryid;
    public final PString<Product> name;
    public final PString<Product> logo;
    public final PString<Product> descn;`

**Comment by codefollower** [comment]
> model里面字段是小写的：
> 
> `public class Product extends Model {
> 
> ```
> public static final Product dao = new Product(null, ROOT_DAO);
> 
> public final PString<Product> productid;
> public final PString<Product> categoryid;
> public final PString<Product> name;
> public final PString<Product> logo;
> public final PString<Product> descn;`
> ```

构造函数里的才是字段名，不过这个问题在 lealone-5.0.1-SNAPSHOT 已经修复了。
