### ISSUE TITLE
Mac下运行文件路径问题

### ISSUE THREAD

**Issue by liujian16** [lealone/Lealone-Examples#3]
浏览器打不开页面。看异常应该是处理路由时计算文件路径的问题。预编译时也有类似问题，把模板中的`/fragment/user/login.html`改成`fragment/user/login.html`能跑过去。
<img width="1016" alt="屏幕快照 2020-12-31 10 26 29" src="https://user-images.githubusercontent.com/1186244/103391189-09941300-4b53-11eb-84d0-65f05cfa3c90.png">

```
INFO 10:25:14.576 Lealone version: 5.0.0-SNAPSHOT
INFO 10:25:14.590 Loading config from file:/Users/xxx/codework/Lealone-Examples/petstore/petstore-test/target/test-classes/lealone.yaml
INFO 10:25:14.735 Base dir: ./target/data
INFO 10:25:14.800 Init storage engines: 11 ms
INFO 10:25:14.924 Init transaction engines: 123 ms
INFO 10:25:14.928 Init sql engines: 3 ms
INFO 10:25:14.971 Init protocol server engines: 43 ms
INFO 10:25:15.166 Init lealone database: 195 ms
INFO 10:25:15.166 Starting nio net server
INFO 10:25:15.196 TcpServer started, host: 127.0.0.1, port: 9210
INFO 10:25:15.701 Web root: ../petstore-web/web
INFO 10:25:15.701 Sockjs path: /_lealone_sockjs_/*
INFO 10:25:15.701 HttpServer is now listening on port: 9000
INFO 10:25:15.701 HttpServer started, host: 127.0.0.1, port: 9000
INFO 10:25:15.701 Total time: 1119 ms (Load config: 153 ms, Init: 431 ms, Start: 535 ms)
INFO 10:25:15.702 Exit with Ctrl+C
ERROR 10:26:40.747 [THYMELEAF][vert.x-eventloop-thread-0] Exception processing template "/home/index.html": java.nio.file.NoSuchFileException: /home/index.html
io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: /home/index.html
	at io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1045) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1037) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.vertx.core.file.impl.FileSystemImpl.readFileBlocking(FileSystemImpl.java:418) ~[vertx-core-4.0.0.jar:4.0.0]
	at org.lealone.examples.petstore.web.PetStoreThymeleafTemplateEngine$ResourceTemplateResolver.computeTemplateResource(PetStoreThymeleafTemplateEngine.java:171) ~[classes/:na]
	at org.thymeleaf.templateresolver.AbstractTemplateResolver.resolveTemplate(AbstractTemplateResolver.java:356) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:845) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098) [thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1067) [thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
	at org.lealone.examples.petstore.web.PetStoreThymeleafTemplateEngine.render(PetStoreThymeleafTemplateEngine.java:95) [classes/:na]
	at io.vertx.ext.web.common.template.TemplateEngine.render(TemplateEngine.java:52) [vertx-web-common-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.common.template.TemplateEngine.render(TemplateEngine.java:62) [vertx-web-common-4.0.0.jar:4.0.0]
	at org.lealone.examples.petstore.web.PetStoreRouterFactory.lambda$6(PetStoreRouterFactory.java:103) [classes/:na]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1104) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:131) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$handle$6(SessionHandlerImpl.java:312) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$doGetSession$8(SessionHandlerImpl.java:376) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.sstore.impl.LocalSessionStoreImpl.get(LocalSessionStoreImpl.java:88) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.doGetSession(SessionHandlerImpl.java:361) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.getSession(SessionHandlerImpl.java:357) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.handle(SessionHandlerImpl.java:284) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.handle(SessionHandlerImpl.java:37) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1104) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:131) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:169) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:41) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1104) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:131) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:55) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37) ~[vertx-web-4.0.0.jar:4.0.0]
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:67) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:30) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:52) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:194) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:140) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:151) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101) ~[netty-codec-http-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:115) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38) ~[vertx-core-4.0.0.jar:4.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
Caused by: java.nio.file.NoSuchFileException: /home/index.html
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_92]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_92]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_92]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_92]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[na:1.8.0_92]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[na:1.8.0_92]
	at java.nio.file.Files.readAllBytes(Files.java:3152) ~[na:1.8.0_92]
	at io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1041) ~[vertx-core-4.0.0.jar:4.0.0]
	... 74 common frames omitted
```

**Comment by codefollower** [comment]
@liujian16 
你在 IDE 里面执行 PetStoreDemoTest 的当前目录是什么？
如果 IDE 是 Eclipse 的话，当前目录就是 Lealone-Examples/petstore/petstore-test。

判断当前目录是哪个？可以在 PetStoreDemoTest 类的 main 方法加一行代码:
`System.out.println(new File(".").getCanonicalPath());`

petstore-test/src/test/resources/lealone.yaml 这个配置文件里有个 web_root 参数，默认是 ../petstore-web/web，
如果当前目录是 Lealone-Examples/petstore/petstore-test，web_root是 ../petstore-web/web，那就对了，
如果当前目录不是 Lealone-Examples/petstore/petstore-test，修改一下 web_root 即可。

**Comment by liujian16** [comment]
@codefollower 
找到原因了。是`org.lealone.examples.petstore.web.PetStoreThymeleafTemplateEngine.computeTemplateResource`的问题

```java
            File file = new File(template);
            if (!file.isAbsolute()) {
                file = new File(templateRoot, template);
                template = file.getAbsolutePath();
            }
```
在*nix系统下`/home/index.html`会被当作绝对路径，这样就绕过了`webRoot`。我删掉了`file.isAbsolute()`那行就好了。
