### ISSUE TITLE
orm-demo

### ISSUE THREAD

**Issue by jiliapp** [lealone/Lealone-Examples#9]
1. 本地启动一个lealone服务

2. 更换prm-demo中的
 jdbcUrl String jdbcUrl = "jdbc:lealone:embed:test";
 地址为
String jdbcUrl = "jdbc:lealone:tcp://127.0.0.1:9210/lealone;password=;user=root";

报错误
````

  // 单表crud操作
    static void testCrud() {
        // insert
        new Customer().id.set(1001).name.set("rob").phone.set(12345678).insert(); //此处报错找不到表结构
}
Exception in thread "main" org.lealone.common.exceptions.DbException: Table "CUSTOMER" not found [42102-0]
	at org.lealone.common.exceptions.DbException.get(DbException.java:172)
	at org.lealone.common.exceptions.DbException.get(DbException.java:149)
	at org.lealone.db.schema.Schema.getTableOrView(Schema.java:566)
	at org.lealone.orm.ModelTable.attachToTable(ModelTable.java:89)
	at org.lealone.orm.ModelTable.getSession(ModelTable.java:55)
	at org.lealone.orm.Model.getSession(Model.java:662)
	at org.lealone.orm.Model.insert(Model.java:687)
	at org.lealone.orm.Model.insert(Model.java:673)
	at org.lealone.examples.orm.OrmDemo.testCrud(OrmDemo.java:45)
	at org.lealone.examples.orm.OrmDemo.main(OrmDemo.java:35)
Caused by: org.lealone.common.exceptions.JdbcSQLException: Table "CUSTOMER" not found [42102-0]
	at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:340)
````

实际在sqlshell中show tables 可以看到表

````
+------------+--------------+
| TABLE_NAME | TABLE_SCHEMA |
+------------+--------------+
| CUSTOMER   | PUBLIC       |
| ORDER          | PUBLIC       |
+------------+--------------+

````

**Comment by codefollower** [comment]
lealone orm 目前的设计是刻意只针对嵌入式场景的，暂不支持访问远程数据库。
